### ISSUE TITLE
Workflow engine doesn't stop/terminate after last task

### ISSUE THREAD

**Issue by arnoldtonderaimarunda** [linkyndy/pallets#63]
Hi @linkyndy,

Could you please advise how I get the workflow to stop after successfully performing the last task. 
Currently I need to Ctrl-C to terminate the workflow. 
Tried to unsuccessfully add `exit(true)`

**Comment by linkyndy** [comment]
Hi @arnoldtonderaimarunda! The workflow is done after performing all of its tasks. The `pallets` process will keep running and waiting for any other workflow to come in. You can kill it like you would kill any other process (`^C` will do).

**Comment by arnoldtonderaimarunda** [comment]
Hi @linkyndy, so confirm there is no way within Pallets to programatically kill the process?

**Comment by linkyndy** [comment]
No, not at the moment. Pallets' process works in a similar way to Puma or Sidekiq, i.e. you start the process, you start workflows that need to be processed, and then kill the process when you desire; ideally, it should run for extended periods of time.

What would be the use-case for what you are proposing?

**Comment by arnoldtonderaimarunda** [comment]
Understood. I do have a workaround, but had been curious if Pallets had an inbuilt method.
I'm using Pallets to power a scheduled workflow that will run every Monday. Would ideally want it to be off all the other days of the week.

**Comment by linkyndy** [comment]
I understand. I think you'll be better off with a process scheduler in this case, as those tools are more robust and made for this specific reason 😊
